// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: component/camera/v1/camera.proto

package v1

import (
	v11 "go.viam.com/api/app/data/v1"
	v1 "go.viam.com/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_FORMAT_UNSPECIFIED Format = 0
	Format_FORMAT_RAW_RGBA    Format = 1
	Format_FORMAT_RAW_DEPTH   Format = 2
	Format_FORMAT_JPEG        Format = 3
	Format_FORMAT_PNG         Format = 4
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_RAW_RGBA",
		2: "FORMAT_RAW_DEPTH",
		3: "FORMAT_JPEG",
		4: "FORMAT_PNG",
	}
	Format_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_RAW_RGBA":    1,
		"FORMAT_RAW_DEPTH":   2,
		"FORMAT_JPEG":        3,
		"FORMAT_PNG":         4,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_component_camera_v1_camera_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_component_camera_v1_camera_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{0}
}

type GetImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of a camera
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Requested MIME type of response
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Additional arguments to the method
	Extra         *structpb.Struct `protobuf:"bytes,99,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{0}
}

func (x *GetImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetImageRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetImageRequest) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type GetImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Actual MIME type of response
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Frame in bytes
	Image         []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageResponse) Reset() {
	*x = GetImageResponse{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageResponse) ProtoMessage() {}

func (x *GetImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageResponse.ProtoReflect.Descriptor instead.
func (*GetImageResponse) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{1}
}

func (x *GetImageResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetImageResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type GetImagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of a camera
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The names of the sensors to retrieve images from. If this is not provided,
	// all images from all sensors will be returned.
	FilterSourceNames []string `protobuf:"bytes,2,rep,name=filter_source_names,json=filterSourceNames,proto3" json:"filter_source_names,omitempty"`
	// Additional arguments to the method
	Extra         *structpb.Struct `protobuf:"bytes,99,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImagesRequest) Reset() {
	*x = GetImagesRequest{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImagesRequest) ProtoMessage() {}

func (x *GetImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImagesRequest.ProtoReflect.Descriptor instead.
func (*GetImagesRequest) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{2}
}

func (x *GetImagesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetImagesRequest) GetFilterSourceNames() []string {
	if x != nil {
		return x.FilterSourceNames
	}
	return nil
}

func (x *GetImagesRequest) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type GetImagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of images returned from the camera system
	Images []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	// contains timestamp data
	ResponseMetadata *v1.ResponseMetadata `protobuf:"bytes,84260,opt,name=response_metadata,json=responseMetadata,proto3" json:"response_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetImagesResponse) Reset() {
	*x = GetImagesResponse{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImagesResponse) ProtoMessage() {}

func (x *GetImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImagesResponse.ProtoReflect.Descriptor instead.
func (*GetImagesResponse) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{3}
}

func (x *GetImagesResponse) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GetImagesResponse) GetResponseMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.ResponseMetadata
	}
	return nil
}

type Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of the sensor where the image came from
	SourceName string `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	// format of the response image bytes
	Format Format `protobuf:"varint,2,opt,name=format,proto3,enum=viam.component.camera.v1.Format" json:"format,omitempty"`
	// image in bytes
	Image []byte `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// The mime type of the image
	MimeType string `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// annotations can be used to store additional information about the image
	Annotations   *v11.Annotations `protobuf:"bytes,5,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{4}
}

func (x *Image) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Image) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_UNSPECIFIED
}

func (x *Image) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Image) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Image) GetAnnotations() *v11.Annotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type RenderFrameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of a camera
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Requested MIME type of response
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Additional arguments to the method
	Extra         *structpb.Struct `protobuf:"bytes,99,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderFrameRequest) Reset() {
	*x = RenderFrameRequest{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderFrameRequest) ProtoMessage() {}

func (x *RenderFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderFrameRequest.ProtoReflect.Descriptor instead.
func (*RenderFrameRequest) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{5}
}

func (x *RenderFrameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RenderFrameRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *RenderFrameRequest) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type GetPointCloudRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of a camera
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Requested MIME type of response
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Additional arguments to the method
	Extra         *structpb.Struct `protobuf:"bytes,99,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointCloudRequest) Reset() {
	*x = GetPointCloudRequest{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointCloudRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointCloudRequest) ProtoMessage() {}

func (x *GetPointCloudRequest) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointCloudRequest.ProtoReflect.Descriptor instead.
func (*GetPointCloudRequest) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{6}
}

func (x *GetPointCloudRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPointCloudRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetPointCloudRequest) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type GetPointCloudResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Actual MIME type of response
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Frame in bytes
	PointCloud    []byte `protobuf:"bytes,2,opt,name=point_cloud,json=pointCloud,proto3" json:"point_cloud,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointCloudResponse) Reset() {
	*x = GetPointCloudResponse{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointCloudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointCloudResponse) ProtoMessage() {}

func (x *GetPointCloudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointCloudResponse.ProtoReflect.Descriptor instead.
func (*GetPointCloudResponse) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{7}
}

func (x *GetPointCloudResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetPointCloudResponse) GetPointCloud() []byte {
	if x != nil {
		return x.PointCloud
	}
	return nil
}

type GetPropertiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of a camera
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertiesRequest) Reset() {
	*x = GetPropertiesRequest{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertiesRequest) ProtoMessage() {}

func (x *GetPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertiesRequest.ProtoReflect.Descriptor instead.
func (*GetPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{8}
}

func (x *GetPropertiesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPropertiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A boolean property determining whether the camera supports the return of pointcloud data
	SupportsPcd bool `protobuf:"varint,1,opt,name=supports_pcd,json=supportsPcd,proto3" json:"supports_pcd,omitempty"`
	// Parameters for doing a perspective of a 3D scene to a 2D plane
	// If camera does not provide intrinsic parameters, leave the field empty
	// Initializing the parameters with 0-values is considered an error
	IntrinsicParameters *IntrinsicParameters `protobuf:"bytes,2,opt,name=intrinsic_parameters,json=intrinsicParameters,proto3" json:"intrinsic_parameters,omitempty"`
	// Parameters for modeling lens distortion in cameras
	// If camera does not provide distortion parameters, leave the field empty
	// Initializing the parameters with 0-values is considered an error
	DistortionParameters *DistortionParameters `protobuf:"bytes,3,opt,name=distortion_parameters,json=distortionParameters,proto3" json:"distortion_parameters,omitempty"`
	// Supported MIME types by the camera
	MimeTypes []string `protobuf:"bytes,4,rep,name=mime_types,json=mimeTypes,proto3" json:"mime_types,omitempty"`
	// Optional camera frame rate for image capture timing
	FrameRate *float32 `protobuf:"fixed32,5,opt,name=frame_rate,json=frameRate,proto3,oneof" json:"frame_rate,omitempty"`
	// Parameters for the camera's position and orientation relative to a reference frame
	// If camera does not provide extrinsic parameters, leave the field empty
	ExtrinsicParameters *ExtrinsicParameters `protobuf:"bytes,6,opt,name=extrinsic_parameters,json=extrinsicParameters,proto3" json:"extrinsic_parameters,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetPropertiesResponse) Reset() {
	*x = GetPropertiesResponse{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertiesResponse) ProtoMessage() {}

func (x *GetPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertiesResponse.ProtoReflect.Descriptor instead.
func (*GetPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{9}
}

func (x *GetPropertiesResponse) GetSupportsPcd() bool {
	if x != nil {
		return x.SupportsPcd
	}
	return false
}

func (x *GetPropertiesResponse) GetIntrinsicParameters() *IntrinsicParameters {
	if x != nil {
		return x.IntrinsicParameters
	}
	return nil
}

func (x *GetPropertiesResponse) GetDistortionParameters() *DistortionParameters {
	if x != nil {
		return x.DistortionParameters
	}
	return nil
}

func (x *GetPropertiesResponse) GetMimeTypes() []string {
	if x != nil {
		return x.MimeTypes
	}
	return nil
}

func (x *GetPropertiesResponse) GetFrameRate() float32 {
	if x != nil && x.FrameRate != nil {
		return *x.FrameRate
	}
	return 0
}

func (x *GetPropertiesResponse) GetExtrinsicParameters() *ExtrinsicParameters {
	if x != nil {
		return x.ExtrinsicParameters
	}
	return nil
}

type Webcams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webcams       []*Webcam              `protobuf:"bytes,1,rep,name=webcams,proto3" json:"webcams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Webcams) Reset() {
	*x = Webcams{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webcams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webcams) ProtoMessage() {}

func (x *Webcams) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webcams.ProtoReflect.Descriptor instead.
func (*Webcams) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{10}
}

func (x *Webcams) GetWebcams() []*Webcam {
	if x != nil {
		return x.Webcams
	}
	return nil
}

type Webcam struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Camera driver label (for internal use only)
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// Camera driver status
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Camera properties
	Properties []*Property `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty"`
	// Camera human-readable driver name
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Camera unique identifier
	Id            string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Webcam) Reset() {
	*x = Webcam{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webcam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webcam) ProtoMessage() {}

func (x *Webcam) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webcam.ProtoReflect.Descriptor instead.
func (*Webcam) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{11}
}

func (x *Webcam) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Webcam) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Webcam) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Webcam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Webcam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Property struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Video resolution width in px
	WidthPx int32 `protobuf:"varint,1,opt,name=width_px,json=widthPx,proto3" json:"width_px,omitempty"`
	// Video resolution height in px
	HeightPx int32 `protobuf:"varint,2,opt,name=height_px,json=heightPx,proto3" json:"height_px,omitempty"`
	// Video frame format
	FrameFormat string `protobuf:"bytes,3,opt,name=frame_format,json=frameFormat,proto3" json:"frame_format,omitempty"`
	// Video frame rate in fps
	FrameRate     float32 `protobuf:"fixed32,4,opt,name=frame_rate,json=frameRate,proto3" json:"frame_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{12}
}

func (x *Property) GetWidthPx() int32 {
	if x != nil {
		return x.WidthPx
	}
	return 0
}

func (x *Property) GetHeightPx() int32 {
	if x != nil {
		return x.HeightPx
	}
	return 0
}

func (x *Property) GetFrameFormat() string {
	if x != nil {
		return x.FrameFormat
	}
	return ""
}

func (x *Property) GetFrameRate() float32 {
	if x != nil {
		return x.FrameRate
	}
	return 0
}

type IntrinsicParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidthPx       uint32                 `protobuf:"varint,1,opt,name=width_px,json=widthPx,proto3" json:"width_px,omitempty"`
	HeightPx      uint32                 `protobuf:"varint,2,opt,name=height_px,json=heightPx,proto3" json:"height_px,omitempty"`
	FocalXPx      float64                `protobuf:"fixed64,3,opt,name=focal_x_px,json=focalXPx,proto3" json:"focal_x_px,omitempty"`
	FocalYPx      float64                `protobuf:"fixed64,4,opt,name=focal_y_px,json=focalYPx,proto3" json:"focal_y_px,omitempty"`
	CenterXPx     float64                `protobuf:"fixed64,5,opt,name=center_x_px,json=centerXPx,proto3" json:"center_x_px,omitempty"`
	CenterYPx     float64                `protobuf:"fixed64,6,opt,name=center_y_px,json=centerYPx,proto3" json:"center_y_px,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrinsicParameters) Reset() {
	*x = IntrinsicParameters{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrinsicParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrinsicParameters) ProtoMessage() {}

func (x *IntrinsicParameters) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrinsicParameters.ProtoReflect.Descriptor instead.
func (*IntrinsicParameters) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{13}
}

func (x *IntrinsicParameters) GetWidthPx() uint32 {
	if x != nil {
		return x.WidthPx
	}
	return 0
}

func (x *IntrinsicParameters) GetHeightPx() uint32 {
	if x != nil {
		return x.HeightPx
	}
	return 0
}

func (x *IntrinsicParameters) GetFocalXPx() float64 {
	if x != nil {
		return x.FocalXPx
	}
	return 0
}

func (x *IntrinsicParameters) GetFocalYPx() float64 {
	if x != nil {
		return x.FocalYPx
	}
	return 0
}

func (x *IntrinsicParameters) GetCenterXPx() float64 {
	if x != nil {
		return x.CenterXPx
	}
	return 0
}

func (x *IntrinsicParameters) GetCenterYPx() float64 {
	if x != nil {
		return x.CenterYPx
	}
	return 0
}

type DistortionParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Parameters    []float64              `protobuf:"fixed64,2,rep,packed,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistortionParameters) Reset() {
	*x = DistortionParameters{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistortionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistortionParameters) ProtoMessage() {}

func (x *DistortionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistortionParameters.ProtoReflect.Descriptor instead.
func (*DistortionParameters) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{14}
}

func (x *DistortionParameters) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DistortionParameters) GetParameters() []float64 {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// ExtrinsicParameters define the position and orientation of the camera
// relative to a reference frame (the world or another sensor).
type ExtrinsicParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The pose of the camera in the reference frame
	Pose          *v1.Pose `protobuf:"bytes,1,opt,name=pose,proto3" json:"pose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtrinsicParameters) Reset() {
	*x = ExtrinsicParameters{}
	mi := &file_component_camera_v1_camera_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtrinsicParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtrinsicParameters) ProtoMessage() {}

func (x *ExtrinsicParameters) ProtoReflect() protoreflect.Message {
	mi := &file_component_camera_v1_camera_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtrinsicParameters.ProtoReflect.Descriptor instead.
func (*ExtrinsicParameters) Descriptor() ([]byte, []int) {
	return file_component_camera_v1_camera_proto_rawDescGZIP(), []int{15}
}

func (x *ExtrinsicParameters) GetPose() *v1.Pose {
	if x != nil {
		return x.Pose
	}
	return nil
}

var File_component_camera_v1_camera_proto protoreflect.FileDescriptor

const file_component_camera_v1_camera_proto_rawDesc = "" +
	"\n" +
	" component/camera/v1/camera.proto\x12\x18viam.component.camera.v1\x1a\x16app/data/v1/data.proto\x1a\x16common/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\x1a\x1cgoogle/protobuf/struct.proto\"q\n" +
	"\x0fGetImageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12-\n" +
	"\x05extra\x18c \x01(\v2\x17.google.protobuf.StructR\x05extra\"E\n" +
	"\x10GetImageResponse\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x14\n" +
	"\x05image\x18\x02 \x01(\fR\x05image\"\x85\x01\n" +
	"\x10GetImagesRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x13filter_source_names\x18\x02 \x03(\tR\x11filterSourceNames\x12-\n" +
	"\x05extra\x18c \x01(\v2\x17.google.protobuf.StructR\x05extra\"\x9d\x01\n" +
	"\x11GetImagesResponse\x127\n" +
	"\x06images\x18\x01 \x03(\v2\x1f.viam.component.camera.v1.ImageR\x06images\x12O\n" +
	"\x11response_metadata\x18\xa4\x92\x05 \x01(\v2 .viam.common.v1.ResponseMetadataR\x10responseMetadata\"\xd6\x01\n" +
	"\x05Image\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x128\n" +
	"\x06format\x18\x02 \x01(\x0e2 .viam.component.camera.v1.FormatR\x06format\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12?\n" +
	"\vannotations\x18\x05 \x01(\v2\x1d.viam.app.data.v1.AnnotationsR\vannotations\"t\n" +
	"\x12RenderFrameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12-\n" +
	"\x05extra\x18c \x01(\v2\x17.google.protobuf.StructR\x05extra\"v\n" +
	"\x14GetPointCloudRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12-\n" +
	"\x05extra\x18c \x01(\v2\x17.google.protobuf.StructR\x05extra\"U\n" +
	"\x15GetPointCloudResponse\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x1f\n" +
	"\vpoint_cloud\x18\x02 \x01(\fR\n" +
	"pointCloud\"*\n" +
	"\x14GetPropertiesRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xb5\x03\n" +
	"\x15GetPropertiesResponse\x12!\n" +
	"\fsupports_pcd\x18\x01 \x01(\bR\vsupportsPcd\x12`\n" +
	"\x14intrinsic_parameters\x18\x02 \x01(\v2-.viam.component.camera.v1.IntrinsicParametersR\x13intrinsicParameters\x12c\n" +
	"\x15distortion_parameters\x18\x03 \x01(\v2..viam.component.camera.v1.DistortionParametersR\x14distortionParameters\x12\x1d\n" +
	"\n" +
	"mime_types\x18\x04 \x03(\tR\tmimeTypes\x12\"\n" +
	"\n" +
	"frame_rate\x18\x05 \x01(\x02H\x00R\tframeRate\x88\x01\x01\x12`\n" +
	"\x14extrinsic_parameters\x18\x06 \x01(\v2-.viam.component.camera.v1.ExtrinsicParametersR\x13extrinsicParametersB\r\n" +
	"\v_frame_rate\"E\n" +
	"\aWebcams\x12:\n" +
	"\awebcams\x18\x01 \x03(\v2 .viam.component.camera.v1.WebcamR\awebcams\"\x9e\x01\n" +
	"\x06Webcam\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12B\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2\".viam.component.camera.v1.PropertyR\n" +
	"properties\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\"\x84\x01\n" +
	"\bProperty\x12\x19\n" +
	"\bwidth_px\x18\x01 \x01(\x05R\awidthPx\x12\x1b\n" +
	"\theight_px\x18\x02 \x01(\x05R\bheightPx\x12!\n" +
	"\fframe_format\x18\x03 \x01(\tR\vframeFormat\x12\x1d\n" +
	"\n" +
	"frame_rate\x18\x04 \x01(\x02R\tframeRate\"\xc9\x01\n" +
	"\x13IntrinsicParameters\x12\x19\n" +
	"\bwidth_px\x18\x01 \x01(\rR\awidthPx\x12\x1b\n" +
	"\theight_px\x18\x02 \x01(\rR\bheightPx\x12\x1c\n" +
	"\n" +
	"focal_x_px\x18\x03 \x01(\x01R\bfocalXPx\x12\x1c\n" +
	"\n" +
	"focal_y_px\x18\x04 \x01(\x01R\bfocalYPx\x12\x1e\n" +
	"\vcenter_x_px\x18\x05 \x01(\x01R\tcenterXPx\x12\x1e\n" +
	"\vcenter_y_px\x18\x06 \x01(\x01R\tcenterYPx\"L\n" +
	"\x14DistortionParameters\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x03(\x01R\n" +
	"parameters\"?\n" +
	"\x13ExtrinsicParameters\x12(\n" +
	"\x04pose\x18\x01 \x01(\v2\x14.viam.common.v1.PoseR\x04pose*l\n" +
	"\x06Format\x12\x16\n" +
	"\x12FORMAT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFORMAT_RAW_RGBA\x10\x01\x12\x14\n" +
	"\x10FORMAT_RAW_DEPTH\x10\x02\x12\x0f\n" +
	"\vFORMAT_JPEG\x10\x03\x12\x0e\n" +
	"\n" +
	"FORMAT_PNG\x10\x042\xcf\b\n" +
	"\rCameraService\x12\x95\x01\n" +
	"\bGetImage\x12).viam.component.camera.v1.GetImageRequest\x1a*.viam.component.camera.v1.GetImageResponse\"2\x82\xd3\xe4\x93\x02,\x12*/viam/api/v1/component/camera/{name}/image\x12\x99\x01\n" +
	"\tGetImages\x12*.viam.component.camera.v1.GetImagesRequest\x1a+.viam.component.camera.v1.GetImagesResponse\"3\x82\xd3\xe4\x93\x02-\x12+/viam/api/v1/component/camera/{name}/images\x12\x8c\x01\n" +
	"\vRenderFrame\x12,.viam.component.camera.v1.RenderFrameRequest\x1a\x14.google.api.HttpBody\"9\x82\xd3\xe4\x93\x023\x121/viam/api/v1/component/camera/{name}/render_frame\x12\xaa\x01\n" +
	"\rGetPointCloud\x12..viam.component.camera.v1.GetPointCloudRequest\x1a/.viam.component.camera.v1.GetPointCloudResponse\"8\x82\xd3\xe4\x93\x022\x120/viam/api/v1/component/camera/{name}/point_cloud\x12\xa9\x01\n" +
	"\rGetProperties\x12..viam.component.camera.v1.GetPropertiesRequest\x1a/.viam.component.camera.v1.GetPropertiesResponse\"7\x82\xd3\xe4\x93\x021\x12//viam/api/v1/component/camera/{name}/properties\x12\x89\x01\n" +
	"\tDoCommand\x12 .viam.common.v1.DoCommandRequest\x1a!.viam.common.v1.DoCommandResponse\"7\x82\xd3\xe4\x93\x021\"//viam/api/v1/component/camera/{name}/do_command\x12\x95\x01\n" +
	"\rGetGeometries\x12$.viam.common.v1.GetGeometriesRequest\x1a%.viam.common.v1.GetGeometriesResponse\"7\x82\xd3\xe4\x93\x021\x12//viam/api/v1/component/camera/{name}/geometriesBC\n" +
	"\x1ccom.viam.component.camera.v1Z#go.viam.com/api/component/camera/v1b\x06proto3"

var (
	file_component_camera_v1_camera_proto_rawDescOnce sync.Once
	file_component_camera_v1_camera_proto_rawDescData []byte
)

func file_component_camera_v1_camera_proto_rawDescGZIP() []byte {
	file_component_camera_v1_camera_proto_rawDescOnce.Do(func() {
		file_component_camera_v1_camera_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_component_camera_v1_camera_proto_rawDesc), len(file_component_camera_v1_camera_proto_rawDesc)))
	})
	return file_component_camera_v1_camera_proto_rawDescData
}

var file_component_camera_v1_camera_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_component_camera_v1_camera_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_component_camera_v1_camera_proto_goTypes = []any{
	(Format)(0),                      // 0: viam.component.camera.v1.Format
	(*GetImageRequest)(nil),          // 1: viam.component.camera.v1.GetImageRequest
	(*GetImageResponse)(nil),         // 2: viam.component.camera.v1.GetImageResponse
	(*GetImagesRequest)(nil),         // 3: viam.component.camera.v1.GetImagesRequest
	(*GetImagesResponse)(nil),        // 4: viam.component.camera.v1.GetImagesResponse
	(*Image)(nil),                    // 5: viam.component.camera.v1.Image
	(*RenderFrameRequest)(nil),       // 6: viam.component.camera.v1.RenderFrameRequest
	(*GetPointCloudRequest)(nil),     // 7: viam.component.camera.v1.GetPointCloudRequest
	(*GetPointCloudResponse)(nil),    // 8: viam.component.camera.v1.GetPointCloudResponse
	(*GetPropertiesRequest)(nil),     // 9: viam.component.camera.v1.GetPropertiesRequest
	(*GetPropertiesResponse)(nil),    // 10: viam.component.camera.v1.GetPropertiesResponse
	(*Webcams)(nil),                  // 11: viam.component.camera.v1.Webcams
	(*Webcam)(nil),                   // 12: viam.component.camera.v1.Webcam
	(*Property)(nil),                 // 13: viam.component.camera.v1.Property
	(*IntrinsicParameters)(nil),      // 14: viam.component.camera.v1.IntrinsicParameters
	(*DistortionParameters)(nil),     // 15: viam.component.camera.v1.DistortionParameters
	(*ExtrinsicParameters)(nil),      // 16: viam.component.camera.v1.ExtrinsicParameters
	(*structpb.Struct)(nil),          // 17: google.protobuf.Struct
	(*v1.ResponseMetadata)(nil),      // 18: viam.common.v1.ResponseMetadata
	(*v11.Annotations)(nil),          // 19: viam.app.data.v1.Annotations
	(*v1.Pose)(nil),                  // 20: viam.common.v1.Pose
	(*v1.DoCommandRequest)(nil),      // 21: viam.common.v1.DoCommandRequest
	(*v1.GetGeometriesRequest)(nil),  // 22: viam.common.v1.GetGeometriesRequest
	(*httpbody.HttpBody)(nil),        // 23: google.api.HttpBody
	(*v1.DoCommandResponse)(nil),     // 24: viam.common.v1.DoCommandResponse
	(*v1.GetGeometriesResponse)(nil), // 25: viam.common.v1.GetGeometriesResponse
}
var file_component_camera_v1_camera_proto_depIdxs = []int32{
	17, // 0: viam.component.camera.v1.GetImageRequest.extra:type_name -> google.protobuf.Struct
	17, // 1: viam.component.camera.v1.GetImagesRequest.extra:type_name -> google.protobuf.Struct
	5,  // 2: viam.component.camera.v1.GetImagesResponse.images:type_name -> viam.component.camera.v1.Image
	18, // 3: viam.component.camera.v1.GetImagesResponse.response_metadata:type_name -> viam.common.v1.ResponseMetadata
	0,  // 4: viam.component.camera.v1.Image.format:type_name -> viam.component.camera.v1.Format
	19, // 5: viam.component.camera.v1.Image.annotations:type_name -> viam.app.data.v1.Annotations
	17, // 6: viam.component.camera.v1.RenderFrameRequest.extra:type_name -> google.protobuf.Struct
	17, // 7: viam.component.camera.v1.GetPointCloudRequest.extra:type_name -> google.protobuf.Struct
	14, // 8: viam.component.camera.v1.GetPropertiesResponse.intrinsic_parameters:type_name -> viam.component.camera.v1.IntrinsicParameters
	15, // 9: viam.component.camera.v1.GetPropertiesResponse.distortion_parameters:type_name -> viam.component.camera.v1.DistortionParameters
	16, // 10: viam.component.camera.v1.GetPropertiesResponse.extrinsic_parameters:type_name -> viam.component.camera.v1.ExtrinsicParameters
	12, // 11: viam.component.camera.v1.Webcams.webcams:type_name -> viam.component.camera.v1.Webcam
	13, // 12: viam.component.camera.v1.Webcam.properties:type_name -> viam.component.camera.v1.Property
	20, // 13: viam.component.camera.v1.ExtrinsicParameters.pose:type_name -> viam.common.v1.Pose
	1,  // 14: viam.component.camera.v1.CameraService.GetImage:input_type -> viam.component.camera.v1.GetImageRequest
	3,  // 15: viam.component.camera.v1.CameraService.GetImages:input_type -> viam.component.camera.v1.GetImagesRequest
	6,  // 16: viam.component.camera.v1.CameraService.RenderFrame:input_type -> viam.component.camera.v1.RenderFrameRequest
	7,  // 17: viam.component.camera.v1.CameraService.GetPointCloud:input_type -> viam.component.camera.v1.GetPointCloudRequest
	9,  // 18: viam.component.camera.v1.CameraService.GetProperties:input_type -> viam.component.camera.v1.GetPropertiesRequest
	21, // 19: viam.component.camera.v1.CameraService.DoCommand:input_type -> viam.common.v1.DoCommandRequest
	22, // 20: viam.component.camera.v1.CameraService.GetGeometries:input_type -> viam.common.v1.GetGeometriesRequest
	2,  // 21: viam.component.camera.v1.CameraService.GetImage:output_type -> viam.component.camera.v1.GetImageResponse
	4,  // 22: viam.component.camera.v1.CameraService.GetImages:output_type -> viam.component.camera.v1.GetImagesResponse
	23, // 23: viam.component.camera.v1.CameraService.RenderFrame:output_type -> google.api.HttpBody
	8,  // 24: viam.component.camera.v1.CameraService.GetPointCloud:output_type -> viam.component.camera.v1.GetPointCloudResponse
	10, // 25: viam.component.camera.v1.CameraService.GetProperties:output_type -> viam.component.camera.v1.GetPropertiesResponse
	24, // 26: viam.component.camera.v1.CameraService.DoCommand:output_type -> viam.common.v1.DoCommandResponse
	25, // 27: viam.component.camera.v1.CameraService.GetGeometries:output_type -> viam.common.v1.GetGeometriesResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_component_camera_v1_camera_proto_init() }
func file_component_camera_v1_camera_proto_init() {
	if File_component_camera_v1_camera_proto != nil {
		return
	}
	file_component_camera_v1_camera_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_component_camera_v1_camera_proto_rawDesc), len(file_component_camera_v1_camera_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_component_camera_v1_camera_proto_goTypes,
		DependencyIndexes: file_component_camera_v1_camera_proto_depIdxs,
		EnumInfos:         file_component_camera_v1_camera_proto_enumTypes,
		MessageInfos:      file_component_camera_v1_camera_proto_msgTypes,
	}.Build()
	File_component_camera_v1_camera_proto = out.File
	file_component_camera_v1_camera_proto_goTypes = nil
	file_component_camera_v1_camera_proto_depIdxs = nil
}
