// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: app/cloudslam/v1/cloud_slam.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CloudSLAMServiceClient is the client API for CloudSLAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudSLAMServiceClient interface {
	StartMappingSession(ctx context.Context, in *StartMappingSessionRequest, opts ...grpc.CallOption) (*StartMappingSessionResponse, error)
	GetActiveMappingSessionsForRobot(ctx context.Context, in *GetActiveMappingSessionsForRobotRequest, opts ...grpc.CallOption) (*GetActiveMappingSessionsForRobotResponse, error)
	GetMappingSessionPointCloud(ctx context.Context, in *GetMappingSessionPointCloudRequest, opts ...grpc.CallOption) (*GetMappingSessionPointCloudResponse, error)
	ListMappingSessions(ctx context.Context, in *ListMappingSessionsRequest, opts ...grpc.CallOption) (*ListMappingSessionsResponse, error)
	StopMappingSession(ctx context.Context, in *StopMappingSessionRequest, opts ...grpc.CallOption) (*StopMappingSessionResponse, error)
}

type cloudSLAMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudSLAMServiceClient(cc grpc.ClientConnInterface) CloudSLAMServiceClient {
	return &cloudSLAMServiceClient{cc}
}

func (c *cloudSLAMServiceClient) StartMappingSession(ctx context.Context, in *StartMappingSessionRequest, opts ...grpc.CallOption) (*StartMappingSessionResponse, error) {
	out := new(StartMappingSessionResponse)
	err := c.cc.Invoke(ctx, "/viam.app.cloudslam.v1.CloudSLAMService/StartMappingSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudSLAMServiceClient) GetActiveMappingSessionsForRobot(ctx context.Context, in *GetActiveMappingSessionsForRobotRequest, opts ...grpc.CallOption) (*GetActiveMappingSessionsForRobotResponse, error) {
	out := new(GetActiveMappingSessionsForRobotResponse)
	err := c.cc.Invoke(ctx, "/viam.app.cloudslam.v1.CloudSLAMService/GetActiveMappingSessionsForRobot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudSLAMServiceClient) GetMappingSessionPointCloud(ctx context.Context, in *GetMappingSessionPointCloudRequest, opts ...grpc.CallOption) (*GetMappingSessionPointCloudResponse, error) {
	out := new(GetMappingSessionPointCloudResponse)
	err := c.cc.Invoke(ctx, "/viam.app.cloudslam.v1.CloudSLAMService/GetMappingSessionPointCloud", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudSLAMServiceClient) ListMappingSessions(ctx context.Context, in *ListMappingSessionsRequest, opts ...grpc.CallOption) (*ListMappingSessionsResponse, error) {
	out := new(ListMappingSessionsResponse)
	err := c.cc.Invoke(ctx, "/viam.app.cloudslam.v1.CloudSLAMService/ListMappingSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudSLAMServiceClient) StopMappingSession(ctx context.Context, in *StopMappingSessionRequest, opts ...grpc.CallOption) (*StopMappingSessionResponse, error) {
	out := new(StopMappingSessionResponse)
	err := c.cc.Invoke(ctx, "/viam.app.cloudslam.v1.CloudSLAMService/StopMappingSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudSLAMServiceServer is the server API for CloudSLAMService service.
// All implementations must embed UnimplementedCloudSLAMServiceServer
// for forward compatibility
type CloudSLAMServiceServer interface {
	StartMappingSession(context.Context, *StartMappingSessionRequest) (*StartMappingSessionResponse, error)
	GetActiveMappingSessionsForRobot(context.Context, *GetActiveMappingSessionsForRobotRequest) (*GetActiveMappingSessionsForRobotResponse, error)
	GetMappingSessionPointCloud(context.Context, *GetMappingSessionPointCloudRequest) (*GetMappingSessionPointCloudResponse, error)
	ListMappingSessions(context.Context, *ListMappingSessionsRequest) (*ListMappingSessionsResponse, error)
	StopMappingSession(context.Context, *StopMappingSessionRequest) (*StopMappingSessionResponse, error)
	mustEmbedUnimplementedCloudSLAMServiceServer()
}

// UnimplementedCloudSLAMServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCloudSLAMServiceServer struct {
}

func (UnimplementedCloudSLAMServiceServer) StartMappingSession(context.Context, *StartMappingSessionRequest) (*StartMappingSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMappingSession not implemented")
}
func (UnimplementedCloudSLAMServiceServer) GetActiveMappingSessionsForRobot(context.Context, *GetActiveMappingSessionsForRobotRequest) (*GetActiveMappingSessionsForRobotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveMappingSessionsForRobot not implemented")
}
func (UnimplementedCloudSLAMServiceServer) GetMappingSessionPointCloud(context.Context, *GetMappingSessionPointCloudRequest) (*GetMappingSessionPointCloudResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMappingSessionPointCloud not implemented")
}
func (UnimplementedCloudSLAMServiceServer) ListMappingSessions(context.Context, *ListMappingSessionsRequest) (*ListMappingSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMappingSessions not implemented")
}
func (UnimplementedCloudSLAMServiceServer) StopMappingSession(context.Context, *StopMappingSessionRequest) (*StopMappingSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopMappingSession not implemented")
}
func (UnimplementedCloudSLAMServiceServer) mustEmbedUnimplementedCloudSLAMServiceServer() {}

// UnsafeCloudSLAMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudSLAMServiceServer will
// result in compilation errors.
type UnsafeCloudSLAMServiceServer interface {
	mustEmbedUnimplementedCloudSLAMServiceServer()
}

func RegisterCloudSLAMServiceServer(s grpc.ServiceRegistrar, srv CloudSLAMServiceServer) {
	s.RegisterService(&CloudSLAMService_ServiceDesc, srv)
}

func _CloudSLAMService_StartMappingSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMappingSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudSLAMServiceServer).StartMappingSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/viam.app.cloudslam.v1.CloudSLAMService/StartMappingSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudSLAMServiceServer).StartMappingSession(ctx, req.(*StartMappingSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudSLAMService_GetActiveMappingSessionsForRobot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveMappingSessionsForRobotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudSLAMServiceServer).GetActiveMappingSessionsForRobot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/viam.app.cloudslam.v1.CloudSLAMService/GetActiveMappingSessionsForRobot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudSLAMServiceServer).GetActiveMappingSessionsForRobot(ctx, req.(*GetActiveMappingSessionsForRobotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudSLAMService_GetMappingSessionPointCloud_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMappingSessionPointCloudRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudSLAMServiceServer).GetMappingSessionPointCloud(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/viam.app.cloudslam.v1.CloudSLAMService/GetMappingSessionPointCloud",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudSLAMServiceServer).GetMappingSessionPointCloud(ctx, req.(*GetMappingSessionPointCloudRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudSLAMService_ListMappingSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMappingSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudSLAMServiceServer).ListMappingSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/viam.app.cloudslam.v1.CloudSLAMService/ListMappingSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudSLAMServiceServer).ListMappingSessions(ctx, req.(*ListMappingSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudSLAMService_StopMappingSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopMappingSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudSLAMServiceServer).StopMappingSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/viam.app.cloudslam.v1.CloudSLAMService/StopMappingSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudSLAMServiceServer).StopMappingSession(ctx, req.(*StopMappingSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudSLAMService_ServiceDesc is the grpc.ServiceDesc for CloudSLAMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudSLAMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "viam.app.cloudslam.v1.CloudSLAMService",
	HandlerType: (*CloudSLAMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartMappingSession",
			Handler:    _CloudSLAMService_StartMappingSession_Handler,
		},
		{
			MethodName: "GetActiveMappingSessionsForRobot",
			Handler:    _CloudSLAMService_GetActiveMappingSessionsForRobot_Handler,
		},
		{
			MethodName: "GetMappingSessionPointCloud",
			Handler:    _CloudSLAMService_GetMappingSessionPointCloud_Handler,
		},
		{
			MethodName: "ListMappingSessions",
			Handler:    _CloudSLAMService_ListMappingSessions_Handler,
		},
		{
			MethodName: "StopMappingSession",
			Handler:    _CloudSLAMService_StopMappingSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/cloudslam/v1/cloud_slam.proto",
}
