// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: component/testecho/v1/testecho.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestEchoService_Echo_FullMethodName         = "/viam.component.testecho.v1.TestEchoService/Echo"
	TestEchoService_EchoMultiple_FullMethodName = "/viam.component.testecho.v1.TestEchoService/EchoMultiple"
	TestEchoService_EchoBiDi_FullMethodName     = "/viam.component.testecho.v1.TestEchoService/EchoBiDi"
	TestEchoService_Stop_FullMethodName         = "/viam.component.testecho.v1.TestEchoService/Stop"
)

// TestEchoServiceClient is the client API for TestEchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestEchoServiceClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	EchoMultiple(ctx context.Context, in *EchoMultipleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoMultipleResponse], error)
	EchoBiDi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoBiDiRequest, EchoBiDiResponse], error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type testEchoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestEchoServiceClient(cc grpc.ClientConnInterface) TestEchoServiceClient {
	return &testEchoServiceClient{cc}
}

func (c *testEchoServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, TestEchoService_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testEchoServiceClient) EchoMultiple(ctx context.Context, in *EchoMultipleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoMultipleResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestEchoService_ServiceDesc.Streams[0], TestEchoService_EchoMultiple_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoMultipleRequest, EchoMultipleResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestEchoService_EchoMultipleClient = grpc.ServerStreamingClient[EchoMultipleResponse]

func (c *testEchoServiceClient) EchoBiDi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoBiDiRequest, EchoBiDiResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestEchoService_ServiceDesc.Streams[1], TestEchoService_EchoBiDi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoBiDiRequest, EchoBiDiResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestEchoService_EchoBiDiClient = grpc.BidiStreamingClient[EchoBiDiRequest, EchoBiDiResponse]

func (c *testEchoServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, TestEchoService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestEchoServiceServer is the server API for TestEchoService service.
// All implementations must embed UnimplementedTestEchoServiceServer
// for forward compatibility.
type TestEchoServiceServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	EchoMultiple(*EchoMultipleRequest, grpc.ServerStreamingServer[EchoMultipleResponse]) error
	EchoBiDi(grpc.BidiStreamingServer[EchoBiDiRequest, EchoBiDiResponse]) error
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedTestEchoServiceServer()
}

// UnimplementedTestEchoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestEchoServiceServer struct{}

func (UnimplementedTestEchoServiceServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedTestEchoServiceServer) EchoMultiple(*EchoMultipleRequest, grpc.ServerStreamingServer[EchoMultipleResponse]) error {
	return status.Errorf(codes.Unimplemented, "method EchoMultiple not implemented")
}
func (UnimplementedTestEchoServiceServer) EchoBiDi(grpc.BidiStreamingServer[EchoBiDiRequest, EchoBiDiResponse]) error {
	return status.Errorf(codes.Unimplemented, "method EchoBiDi not implemented")
}
func (UnimplementedTestEchoServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedTestEchoServiceServer) mustEmbedUnimplementedTestEchoServiceServer() {}
func (UnimplementedTestEchoServiceServer) testEmbeddedByValue()                         {}

// UnsafeTestEchoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestEchoServiceServer will
// result in compilation errors.
type UnsafeTestEchoServiceServer interface {
	mustEmbedUnimplementedTestEchoServiceServer()
}

func RegisterTestEchoServiceServer(s grpc.ServiceRegistrar, srv TestEchoServiceServer) {
	// If the following call pancis, it indicates UnimplementedTestEchoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestEchoService_ServiceDesc, srv)
}

func _TestEchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestEchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestEchoService_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestEchoServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestEchoService_EchoMultiple_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EchoMultipleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestEchoServiceServer).EchoMultiple(m, &grpc.GenericServerStream[EchoMultipleRequest, EchoMultipleResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestEchoService_EchoMultipleServer = grpc.ServerStreamingServer[EchoMultipleResponse]

func _TestEchoService_EchoBiDi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestEchoServiceServer).EchoBiDi(&grpc.GenericServerStream[EchoBiDiRequest, EchoBiDiResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestEchoService_EchoBiDiServer = grpc.BidiStreamingServer[EchoBiDiRequest, EchoBiDiResponse]

func _TestEchoService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestEchoServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestEchoService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestEchoServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestEchoService_ServiceDesc is the grpc.ServiceDesc for TestEchoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestEchoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "viam.component.testecho.v1.TestEchoService",
	HandlerType: (*TestEchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _TestEchoService_Echo_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _TestEchoService_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EchoMultiple",
			Handler:       _TestEchoService_EchoMultiple_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EchoBiDi",
			Handler:       _TestEchoService_EchoBiDi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "component/testecho/v1/testecho.proto",
}
