name: On PR Approved

on:
  pull_request_review:
    branches: [ 'main' ]
    types: [submitted]

jobs:
  export_pr_info:
    name: Export Pull Request Info
    runs-on: [self-hosted, x64]
    if: github.event.review.state == 'approved' && github.repository_owner == 'viamrobotics'
    steps:
      - name: Save PR repo and ref
        run: |
          mkdir -p ./pr
          echo ${{ github.event.pull_request.head.repo.full_name }} > ./pr/repo
          echo ${{ github.event.pull_request.head.ref }} > ./pr/ref
          echo ${{ github.event.pull_request.number }} > ./pr/number
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
